### ISSUE TITLE
How to implement this?

### ISSUE THREAD

**Issue by yahyaerturan** [harmony-project/ui-bundle#2]
Hi, I am becoming a huge fan of Semantic UI. I am using Symfony 3.4 LTS. First, thanks for this repo. Can you tell a bit how to use it?

**Comment by codedmonkey** [comment]
Glad you like it. I really messed up on documenting this one, so I added some documentation for the two main features today, which are the Semantic UI form theme and the menu theme for KnpMenuBundle. You can find it here: http://harmony-project.io/docs/ui-bundle. I'm planning to add more examples and hopefully some previews, so feel free to ask for more information if anything isn't clear enough.

**Comment by yahyaerturan** [comment]
@codedmonkey Thank you fy documentation. With version 1.1.2 it works like a charm (as I tested only Forms).

In Symfony 3.4.1, `Harmony\Bundle\UiBundle\HarmonyUiBundle::class => ['all' => true],` automatically added to `bundles.php`.

In `templates/*.html.twig` files, I added `{% form_theme form '@HarmonyUi/form/semantic_2_layout.html.twig' %}` . I wrote those for future reference. :) Thanks again.
